### ISSUE TITLE
Support of Rails 2.1.3 doesn't work

### ISSUE THREAD

**Issue by IanWhitney** [stffn/declarative_authorization#32]
Currently the documentation says that this plugin should work in Rails >= 2.1. But I can't get it to work in 2.1.3. I get the following exception

undefined method `each_with_object' for [:new, :create]:Array
...

vendor/plugins/declarative_authorization/lib/declarative_authorization/in_controller.rb:549:in `actions_from_option'

vendor/plugins/declarative_authorization/lib/declarative_authorization/in_controller.rb:447:in `filter_resource_access'

From what I can see, the each_with_object method wasn't added until Rails 2.2. http://guides.rubyonrails.org/2_2_release_notes.html

**Comment by stffn** [comment]
Any reason to stay with 2.1?  2.2 is from November 2008.  Maybe we should just raise the bar to 2.2...

**Comment by IanWhitney** [comment]
Oh, believe me, I would upgrade if I could. I raised this issue mostly so that you could update your documentation to show that the plugin needs >= 2.2. Thanks for the reply.

**Comment by stffn** [comment]
Yes, sadly, it's the easier solution.
