### ISSUE TITLE
with_permissions_to not working in rails 4.1.6

### ISSUE THREAD

**Issue by fseefried** [stffn/declarative_authorization#199]
Is this a defect or a configuration issue? Please help.

 tickets=Ticket.with_permissions_to(:read)

breaks with:

undefined local variable or method `scoped' for #Class:0x5a207c0

Trace:

activerecord (4.1.6) lib/active_record/dynamic_matchers.rb:26:in `method_missing'
declarative_authorization (0.5.7) lib/declarative_authorization/in_model.rb:108:in`with_permissions_to'
app/controllers/tickets_controller.rb:8:in `index'
actionpack (4.1.6) lib/action_controller/metal/implicit_render.rb:4:in`send_action'
actionpack (4.1.6) lib/abstract_controller/base.rb:189:in `process_action'
actionpack (4.1.6) lib/action_controller/metal/rendering.rb:10:in`process_action'
actionpack (4.1.6) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (4.1.6) lib/active_support/callbacks.rb:113:in`call'

**Comment by fseefried** [comment]
Ok, found out that Model.scoped is depricated in rails 4. But you make it work if you use gem 'activerecord-deprecated_finders'.

Is somebody able to patch this?

**Comment by klyonrad** [comment]
So ehm... the pull request is merged into master. Is this issue closed or open?

**Comment by jphager2** [comment]
Merged, but as far as I can see not released. There hasn't been a release in many years.
